### ISSUE TITLE
Residence Event Illegal Async Call

### ISSUE THREAD

**Issue by Nimaari** [Sefiraat/Networks#132]
Hello!

I'm not really sure what caused this but, a recent update (unsure when) caused my console to be filled with errors in regards to Networks triggering a residence event async. It is pretty much spamming this error every tick (for obvious reasons). Also, ignore the jar names, the auto-updater doesn't change the file name. I am running the latest builds.

Stacktrace:
```
[18:19:55] [Craft Scheduler Thread - 63 - Slimefun/ERROR]: [dough: protection] An Error occured while querying the Protection Module: "Residence v5.1.1.1"
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:659) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:151) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.playerHas(ResidencePermissions.java:72) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.listeners.ResidenceBlockListener.canBreakBlock(ResidenceBlockListener.java:242) ~[Residence5.1.1.1.jar:?]
	at com.bekvon.bukkit.residence.slimeFun.SlimeFunResidenceModule.hasPermission(SlimeFunResidenceModule.java:60) ~[Residence5.1.1.1.jar:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun4 - DEV 1014 (git f431a).jar:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:167) ~[Slimefun4 - DEV 1014 (git f431a).jar:?]
	at io.github.sefiraat.networks.slimefun.network.NetworkControlX.tryBreakBlock(NetworkControlX.java:111) ~[Networks - DEV 34 (git eb71c).jar:?]
	at io.github.sefiraat.networks.slimefun.network.NetworkControlX.onTick(NetworkControlX.java:65) ~[Networks - DEV 34 (git eb71c).jar:?]
	at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:100) ~[Networks - DEV 34 (git eb71c).jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:182) ~[Slimefun4 - DEV 1014 (git f431a).jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:169) ~[Slimefun4 - DEV 1014 (git f431a).jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:139) ~[Slimefun4 - DEV 1014 (git f431a).jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:108) ~[Slimefun4 - DEV 1014 (git f431a).jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
```

Thank you!

**Comment by Sefiraat** [comment]
That’s really useful, thanks @100petr
