### ISSUE TITLE
NTW_Pusher error 

### ISSUE THREAD

**Issue by Kbryst** [Sefiraat/Networks#134]
https://pastebin.com/cNxKDppT

[13:15:35 WARN]: [Networks] 
[13:15:35 WARN]: [Networks] An Error occurred! It has been saved as: 
[13:15:35 WARN]: [Networks] /plugins/Slimefun/error-reports/2023-04-10-13-15.err
[13:15:35 WARN]: [Networks] Please put this file on https://pastebin.com/ and report this to the developer(s).
[13:15:35 WARN]: [Networks] Bug Tracker: https://github.com/Sefiraat/Networks/issues/
[13:15:35 WARN]: [Networks] 
[13:15:38 ERROR]: [Slimefun] X: -8,144 Y: 66 Z: -2,125 (NTW_PUSHER)
[13:15:38 ERROR]: [Slimefun] has thrown 4 error messages in the last 4 Ticks, the Block has been terminated.
[13:15:38 ERROR]: [Slimefun] Check your /plugins/Slimefun/error-reports/ folder for details.
[13:15:38 ERROR]: [Slimefun]  
[13:15:38 ERROR]: [Slimefun] An Exception was caught while ticking the Block Tickers Task for Slimefun vDEV - 1050 (git 22a7f422)
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:138) ~[Slimefun4 - DEV 1028 (git 1dcc4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:108) ~[Slimefun4 - DEV 1028 (git 1dcc4).jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-404]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-404]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by JustAHuman-xD** [comment]
This bug is caused by blockstorage. Block Storage had a menu that was not of a Network Pusher, so it errored while ticking.

**Comment by Sefiraat** [comment]
As above, it looks like a corrupted block that thinks it's a pusher yet the requested BlockMenu is from something else so when it attempted to get the item template to push, it found an inventory that was too small. As the block removed itself then luckily it should be all good - thanks for the report none the less!
