### ISSUE TITLE
Any Networks blocks cannot be placed

### ISSUE THREAD

**Issue by tiandan6666** [Sefiraat/Networks#146]
Error Generated: 2023-07-23-15-37

Java Environment:
  Operating System: Windows 10
  Java Version: 17.0.6

Server Software: Purpur
  Build: git-Purpur-1809 (MC: 1.19.2)
  Minecraft v1.19.2-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v2022.08-release
  Caused by: Networks vBuild 81 (git b321cd1)

Installed Addons (10)
  + SlimyRepair Build 1 zh-CN(baoad) (git d0ae908)
  + GuizhanLibPlugin Build 30 (git c6cce4a)
  + SfChunkInfo Build 8 zh-CN(ybw0014) (git 4ade4ca)
  + EnderCargo Build 1 zh-CN(SlimefunGuguProject) (git 04f339e)
  + SFCalc Build 4 zh-CN(ybw0014) (git ca78ab1)
  + VillagerUtil Build 2 zh-CN(ybw0014) (git f019674)
  + Galactifun Build 17 zh-CN(baoad) (git ec333f0)
  + TranscEndence Build 6 zh-CN(baoad) (git 12c5713)
  + Netheopoiesis Build 11 zh-CN(SlimefunGuguProject) (git 462f4c9)
  + Networks Build 81 (git b321cd1)

Installed Plugins (30):
  + QiQWhiteList v1.0.5
  + WorldEdit 7.2.12+6240-87f4ae1
  + OpenInv 4.2.1
  + PublicBin 1.1.0
  + spark 1.10.43
  + Slimefun 2022.08-release
  + GSit 1.2.8
  + NoEncryption 3.1
  + ViaVersion 4.7.0
  + floodgate 2.2.2-SNAPSHOT (b82-2702bc3)
  + ViaBackwards 4.7.0
  + SlimyRepair Build 1 zh-CN(baoad) (git d0ae908)
  + CoreProtect 21.2
  + LuckPerms 5.4.98
  + GuizhanLibPlugin Build 30 (git c6cce4a)
  + SfChunkInfo Build 8 zh-CN(ybw0014) (git 4ade4ca)
  + BedrockPlayerManager 1.4
  + EnderCargo Build 1 zh-CN(SlimefunGuguProject) (git 04f339e)
  + SFCalc Build 4 zh-CN(ybw0014) (git ca78ab1)
  + VillagerUtil Build 2 zh-CN(ybw0014) (git f019674)
  + Galactifun Build 17 zh-CN(baoad) (git ec333f0)
  + TranscEndence Build 6 zh-CN(baoad) (git 12c5713)
  + Multiverse-Core 4.3.1-b861
  + ProtocolLib 5.0.0-SNAPSHOT-b580
  + SkinsRestorer 14.2.4
  + CatSeedLogin 1.4.1-SNAPSHOT
  + Geyser-Spigot 2.1.0-SNAPSHOT
  + SuperVanish 6.2.11
  + Netheopoiesis Build 11 zh-CN(SlimefunGuguProject) (git 462f4c9)
  + Networks Build 81 (git b321cd1)

Block Info:
  World: world
  X: 94
  Y: 63
  Z: -136
  Material: BLACK_STAINED_GLASS
  Block Data: org.bukkit.craftbukkit.v1_19_R1.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: NTW_CONTROLLER
  Inventory: false
  Data: {"id":"NTW_CONTROLLER"}

Stacktrace:

java.lang.AbstractMethodError: Receiver class io.github.sefiraat.networks.slimefun.network.NetworkController$1 does not define or inherit an implementation of the resolved method 'abstract void tick(org.bukkit.block.Block, io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem, me.mrCookieSlime.CSCoreLibPlugin.Configuration.Config)' of abstract class me.mrCookieSlime.Slimefun.Objects.handlers.BlockTicker.
	at Slimefun-v2022.08-release.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun-v2022.08-release.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at Slimefun-v2022.08-release.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at Slimefun-v2022.08-release.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Sefiraat** [comment]
Sorry but you’ll likely need to raise the issue on the fork of the addon and/or the slimefun fork you are currently using.
