### ISSUE TITLE
Network memory shell deleting itself when with stored vanilla items

### ISSUE THREAD

**Issue by ashlian1200** [Sefiraat/Networks#17]
Like the name says and yes it was connected right and had about 10000 diamonds or so

Error Generated: 2022-01-10-16-49

Java Environment:
  Operating System: Linux
  Java Version: 17.0.1

Server Software: Paper
  Build: git-Paper-68 (MC: 1.18.1)
  Minecraft v1.18.1-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 994 (git eac32ac9)
  Caused by: Networks vMODIFIED_1.0.2

Installed Addons (14)
  + DankTech2 DEV - 4 (git 803760fb)
  + EquivalencyTech ${project.version}
  + SimpleStorage DEV - 10 (git ea5e5637)
  + InfinityExpansion DEV - 130 (git a2773c83)
  + SFCalc DEV - 36 (git 74973a41)
  + MobCapturer DEV - 17 (git c21b00a5)
  + SlimeTinker DEV - 55 (git ec0856ef)
  + Networks MODIFIED_1.0.2
  + FoxyMachines DEV - 51 (git 3493db25)
  + FNAmplifications DEV - 31 (git 0c6ffca5)
  + FlowerPower DEV - 11 (git f12f2f82)
  - Galactifun DEV - 41 (git 364b2dc2)
  + SlimeCustomizer DEV - 23 (git c10380af)
  + CrystamaeHistoria DEV - 31 (git ef67bb1e)

Installed Plugins (56):
  + MedievalFactions 4.4
  + InvSeePlusPlus 0.10.5-SNAPSHOT
  + Slimefun DEV - 994 (git eac32ac9)
  + DankTech2 DEV - 4 (git 803760fb)
  + NBTAPI 2.9.0-SNAPSHOT
  + EquivalencyTech ${project.version}
  + ReviveMe 0.3.9
  + SimpleStorage DEV - 10 (git ea5e5637)
  + CoreProtect 20.1
  + LuckPerms 5.3.47
  + BlueMap 1.7.2
  + InfinityExpansion DEV - 130 (git a2773c83)
  + SFCalc DEV - 36 (git 74973a41)
  + spark 1.6.1
  + MobCapturer DEV - 17 (git c21b00a5)
  + SlimeTinker DEV - 55 (git ec0856ef)
  + ProtocolLib 4.8.0-SNAPSHOT-b538
  + NickAPI 6.3.0
  + LibsDisguises 10.0.27-SNAPSHOT
  + InventoryRollback-Continued 1.5.3
  + Currencies 1.1
  + DeathNote 1.1.2
  + Vault 1.7.3-b131
  + floodgate 2.1.0-SNAPSHOT
  + HaoNick 4.4.0
  + Networks MODIFIED_1.0.2
  + FoxyMachines DEV - 51 (git 3493db25)
  + FNAmplifications DEV - 31 (git 0c6ffca5)
  + FlowerPower DEV - 11 (git f12f2f82)
  - Galactifun DEV - 41 (git 364b2dc2)
  + SlimeCustomizer DEV - 23 (git c10380af)
  + Geyser-Spigot 2.0.0-SNAPSHOT
  + CrystamaeHistoria DEV - 31 (git ef67bb1e)
  + Essentials 2.19.1-dev+53-dc27af7
  + VeinMiner 1.17.9
  + PyroMining 4.3.4
  + AdvancedBan 2.3.0
  + Multiverse-Core 4.3.1-b861
  + SuperVanish 6.2.6
  - EliteMobs 7.3.9
  + MythicMobs 5.0.0-SNAPSHOT-5145f853
  + Multiverse-NetherPortals 4.2.1-b786
  + BloodNight 0.10.7
  + RealisticSeasons 5.3
  + LiquidTanks 2.8.0
  + Kingdoms 1.11.12
  + Oraxen 1.122.0
  + ProMCCore 1.0.3.4-ALPHA
  + ProEnchantmentAPI 1.0-ALPHA
  + ProEnchantmentPack 1.0-ALPHA
  + FactionsBridge 1.3.4
  + EnchantMagicPack 1.0
  + SCore 1.5.8.3
  + ExecutableItems 3.5.8.3
  + WolfyUtilities 1.8.0.0
  + CustomCrafting 1.7.1.3

Block Info:
  World: world
  X: -2147
  Y: 52
  Z: 289
  Material: DEEPSLATE_TILES
  Block Data: org.bukkit.craftbukkit.v1_18_R1.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: NTW_MEMORY_SHELL
  Inventory: true
  Data: {"id":"NTW_MEMORY_SHELL"}

Stacktrace:

java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.hasDisplayName()" because "itemMeta" is null
	at networks.vMODIFIED_1.0.2.jar//io.github.sefiraat.networks.slimefun.tools.CardInstance.getLoreLine(CardInstance.java:80)
	at networks.vMODIFIED_1.0.2.jar//io.github.sefiraat.networks.slimefun.tools.CardInstance.updateLore(CardInstance.java:71)
	at networks.vMODIFIED_1.0.2.jar//io.github.sefiraat.networks.slimefun.network.NetworkMemoryShell.refreshCardLore(NetworkMemoryShell.java:207)
	at networks.vMODIFIED_1.0.2.jar//io.github.sefiraat.networks.slimefun.network.NetworkMemoryShell.tryRefresh(NetworkMemoryShell.java:121)
	at networks.vMODIFIED_1.0.2.jar//io.github.sefiraat.networks.slimefun.network.NetworkMemoryShell$1.tick(NetworkMemoryShell.java:87)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Sefiraat** [comment]
Thanks, found and fixed in the next build
