### ISSUE TITLE
[Bug] Networks Checks Grief Prevention A-Sync

### ISSUE THREAD

**Issue by JustAHuman-xD** [Sefiraat/Networks#171]
The Network Control X and Control V blocks both have permission checks based on who placed them. This makes complete sense to ensure they aren't used to break blocks or place blocks the player can't. 

The issue though is that the blocks run async and some protection plugins do not support checking claims async, in this case, grief prevention. 

![image](https://github.com/Sefiraat/Networks/assets/65748158/0da69a15-a86e-4d71-be19-cbc4621ddf5a)

**Comment by MeowIce** [comment]
> I'm not sure what the best solution would be otherwise I would have opened a PR alr

I also have the same problem.
`[13:55:35 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "GriefPrevention v16.18.3"
java.lang.IllegalStateException: ClaimPermissionCheckEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.ryanhamshire.GriefPrevention.Claim.callPermissionCheck(Claim.java:524) ~[GriefPrevention-16.18.3.jar:?]
        at me.ryanhamshire.GriefPrevention.Claim.checkPermission(Claim.java:484) ~[GriefPrevention-16.18.3.jar:?]
        at me.ryanhamshire.GriefPrevention.Claim.checkPermission(Claim.java:466) ~[GriefPrevention-16.18.3.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.modules.GriefPreventionProtectionModule.checkPermission(GriefPreventionProtectionModule.java:93) ~[Slimefun4-Dev1148.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.modules.GriefPreventionProtectionModule.hasPermission(GriefPreventionProtectionModule.java:69) ~[Slimefun4-Dev1148.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:180) ~[Slimefun4-Dev1148.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:173) ~[Slimefun4-Dev1148.jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkControlV.tryPasteBlock(NetworkControlV.java:129) ~[networks_vMODIFIED_1.2.0.jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkControlV.onTick(NetworkControlV.java:65) ~[networks_vMODIFIED_1.2.0.jar:?]
        at io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:102) ~[networks_vMODIFIED_1.2.0.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:184) ~[Slimefun4-Dev1148.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:171) ~[Slimefun4-Dev1148.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:141) ~[Slimefun4-Dev1148.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:110) ~[Slimefun4-Dev1148.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Sefiraat** [comment]
Hello! GriefPrevention doesn’t allow async permission checks, it’s the only one of the slimefun supported permission managers that does this. I would say that if you want to remain with GreifPrevention you’ll need to remove Networks. The two do. It work with each other I’m afraid!
