### ISSUE TITLE
[BUG]NetworkEncoder can't work

### ISSUE THREAD

**Issue by flyingbee0026** [Sefiraat/Networks#205]
Could not pass event InventoryClickEvent to Slimefun vTEA - 286 (git 3a5dcacb)
java.lang.ExceptionInInitializerError: null
    at io.github.sefiraat.networks.slimefun.network.NetworkEncoder.tryEncode(NetworkEncoder.java:146) ~[Networks - DEV 50 (git 3de3c).jar:?]
    at io.github.sefiraat.networks.slimefun.network.NetworkEncoder$1.lambda$newInstance$1(NetworkEncoder.java:84) ~[Networks - DEV 50 (git 3de3c).jar:?]
    at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:56) ~[Slimefun4 - TEA 286 (git 3a5dc).jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor61.execute(Unknown Source) ~[?:?]

https://youtu.be/WdZYTgVC7nM

**Comment by Sefiraat** [comment]
If you’re able to recreate on the newest version of Networks as well as a development build of Slimefun (not sure what TEA is) then please feel free to reopen this call with the relevant information and I shall take a look :). Thanks for the report refardless.
