### ISSUE TITLE
Dupe potions without base data

### ISSUE THREAD

**Issue by scorninpc** [Sefiraat/Networks#223]
Some plugins create potion without `getBasePotionData()` (like [dropxp](https://github.com/BoltyDawg/DropXP)), so when it's storage into networks, when retrieve, it's crash and dupe the item

```
[15:09:27 ERROR]: Could not pass event InventoryClickEvent to Slimefun vDev - 1157
java.lang.NullPointerException: Cannot invoke "org.bukkit.potion.PotionData.equals(Object)" because the return value of "org.bukkit.inventory.meta.PotionMeta.getBasePotionData()" is null
	at Networks - DEV 50 (git 3de3c).jar/io.github.sefiraat.networks.utils.StackUtils.canQuickEscapeMetaVariant(StackUtils.java:271) ~[Networks - DEV 50 (git 3de3c).jar:?]
	at Networks - DEV 50 (git 3de3c).jar/io.github.sefiraat.networks.utils.StackUtils.itemsMatch(StackUtils.java:80) ~[Networks - DEV 50 (git 3de3c).jar:?]
	at Networks - DEV 50 (git 3de3c).jar/io.github.sefiraat.networks.network.NetworkRoot.getItemStack(NetworkRoot.java:443) ~[Networks - DEV 50 (git 3de3c).jar:?]
	at Networks - DEV 50 (git 3de3c).jar/io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.addToCursor(AbstractGrid.java:308) ~[Networks - DEV 50 (git 3de3c).jar:?]
	at Networks - DEV 50 (git 3de3c).jar/io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.retrieveItem(AbstractGrid.java:278) ~[Networks - DEV 50 (git 3de3c).jar:?]
	at Networks - DEV 50 (git 3de3c).jar/io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.lambda$updateDisplay$1(AbstractGrid.java:196) ~[Networks - DEV 50 (git 3de3c).jar:?]
	at Slimefun4-Dev.jar/me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:53) ~[Slimefun4-Dev.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor29.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2233-0d6766e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3260) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

I fixed doing a simple verification before get `getBasePotioinData()` and works fine

![image](https://github.com/user-attachments/assets/8ec2f349-8535-4400-9a5b-b0fd8615df33)

I dont pull request, becase i dont know if this can afect another things, or if it's better fix `dropxp` plugin

**Comment by 100petr** [comment]
The same error occurs with the CO2 canister from global warming addon.

**Comment by scorninpc** [comment]
> The same error occurs with the CO2 canister from global warming addon.

can you link the addon? i'll try. if occur by the same problem, i'll make a PR

**Comment by 100petr** [comment]
https://github.com/poma123/GlobalWarming
https://pastebin.com/4KBYmgyb
There was no problem on 1.20.2, but it started happening yesterday when I updated to 1.20.6. I haven't tried newer versions.

**Comment by scorninpc** [comment]
I confirm that works fine with https://github.com/Sefiraat/Networks/pull/224

![2024-12-11_19 33 03](https://github.com/user-attachments/assets/21ac564b-32ae-4001-b99d-b0fee4afd9db)
![2024-12-11_19 33 02](https://github.com/user-attachments/assets/86ddf720-aeef-49b3-9e7e-59e9b351d893)

remove fine without dupe or console error

**Comment by 100petr** [comment]
The detail will probably be that the players took the items via grabbers. I will try.

**Comment by scorninpc** [comment]
It seems to have worked 

https://github.com/user-attachments/assets/464f6661-4d73-41d5-9a98-11ac93c4517f

**Comment by 100petr** [comment]
Okay, it doesn't happen anymore. Maybe it only happened with the co2 canisters created in the previous version.
