### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by YangQua** [Sefiraat/Networks#53]
Error Generated: 2022-03-11-20-53

Java Environment:
  Operating System: Windows Server 2016
  Java Version: 17.0.1

Server Software: Paper
  Build: git-Paper-198 (MC: 1.18.1)
  Minecraft v1.18.1-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v4.9-release-2022.01
  Caused by: Networks vBuild 35 zh-CN(ybw0014) (git ae9012b)

Installed Addons (26)
  + EcoPower Build 1 zh-CN(ybw0014) (git eca8ab1)
  + SimpleStorage Build 5 zh-CN(ybw0014) (git c443c7b)
  - GlobalWarming Build 4 zh-CN(ybw0014) (git 9d6b794)
  + SFAdvancements Build 2 zh-CN(ybw0014) (git f0d4be8)
  + SFCalc Build 2 zh-CN(ybw0014) (git dea5970)
  + EMC2 Build 1 zh-TW(SlimeTraditionalTranslation) (git 4a20be4)
  + GeneticChickengineering 1.2.1
  + Liquid Build 1 zh-CN(baoad) (git 972b8dc)
  + LiteXpansion Build 14 zh-CN(ybw0014) (git c7efe19)
  + SoulJars Build 6 zh-CN(ybw0014) (git 7c3d94e)
  + SlimyRepair Build 1 zh-CN(baoad) (git d0ae908)
  + ExtraTools Build 1 zh-CN(baoad) (git 5b1065a)
  + FoxyMachines Build 6 zh-CN(ybw0014) (git b764400)
  + SimpleMaterialGenerators Build 2 zh-TW(SlimeTraditionalTranslation) (git eb7ac7b)
  + ElectricSpawners Build 4 zh-CN(ybw0014) (git 0d7b9bb)
  + VillagerUtil Build 2 zh-CN(ybw0014) (git f019674)
  + FluffyMachines Build 1 zh-CN(baoad) (git eb5d6db)
  + DyedBackpacks Build 1 zh-CN(baoad) (git 823de85)
  + SoundMuffler Build 1 zh-CN(baoad) (git b1678a8)
  + InfinityExpansion 126 zh-CN
  + Networks Build 35 zh-CN(ybw0014) (git ae9012b)
  + DynaTech Build 24 zh-CN(ybw0014) (git ca7d8c6)
  + SlimeTinker Build 32 zh-CN(ybw0014) (git 25590ea)
  + CMILib 1.1.2.0
  + CMI 9.1.3.0
  + Residence 5.0.1.3

Installed Plugins (80):
  + Chunky 1.2.164
  + PlaceholderAPI 2.11.1
  + Boom 1.3.3
  + GuoItemLoreCommand 2.1
  + TrChat 1.90-R6
  + HelloWorld 1.0-SNAPSHOT
  + LuckPerms 5.3.98
  + VoidGen 2.2.1
  + HiveChecker 3.4.4
  + IronElevators 1.6
  + ProtocolLib 4.8.0-SNAPSHOT-b540
  + ILoreEdit 2.4.0
  + LibsDisguises 10.0.27
  + Notbuild 1.5
  + LiteSignIn 1.5.6
  + ShowItem 1.6.17 (build 448)
  + Vault 1.7.3-CMI
  + CrazyCrates 1.10.1
  + Vehicles 13.1
  + TAB-Bridge 1.6.1
  + LuckPermsGUI 4.5
  + PlayerPoints 2.1.4
  + PlayerTitle 2.10.4
  + BeaconPlus2 2.1.60
  + Companions 1.9.2
  + WorldEdit 7.2.8+6008-1246d61
  + HeadDatabase 4.12.0
  + Multiverse-Core 4.3.1-b861
  + TrMenu 3.1.1
  + RainbowsPro 1.2.0
  + AdvancedAchievements 8.0.2
  + WorldGuard 7.0.6+1cff55f
  + Slimefun 4.9-release-2022.01
  + EcoPower Build 1 zh-CN(ybw0014) (git eca8ab1)
  + SimpleStorage Build 5 zh-CN(ybw0014) (git c443c7b)
  + CoreProtect 20.3
  - GlobalWarming Build 4 zh-CN(ybw0014) (git 9d6b794)
  + ShopGUIPlus 1.68.2
  + JetsPrisonMines 4.3.0
  + SFAdvancements Build 2 zh-CN(ybw0014) (git f0d4be8)
  + EvenMoreFish 1.4.4
  + SFCalc Build 2 zh-CN(ybw0014) (git dea5970)
  + EMC2 Build 1 zh-TW(SlimeTraditionalTranslation) (git 4a20be4)
  + GeneticChickengineering 1.2.1
  + Citizens 2.0.29-SNAPSHOT (build 2419)
  + Liquid Build 1 zh-CN(baoad) (git 972b8dc)
  + LiteXpansion Build 14 zh-CN(ybw0014) (git c7efe19)
  + SoulJars Build 6 zh-CN(ybw0014) (git 7c3d94e)
  + SlimyRepair Build 1 zh-CN(baoad) (git d0ae908)
  + EliteMobs 7.3.12
  + ExtraTools Build 1 zh-CN(baoad) (git 5b1065a)
  + FoxyMachines Build 6 zh-CN(ybw0014) (git b764400)
  + SimpleMaterialGenerators Build 2 zh-TW(SlimeTraditionalTranslation) (git eb7ac7b)
  + ElectricSpawners Build 4 zh-CN(ybw0014) (git 0d7b9bb)
  + VillagerUtil Build 2 zh-CN(ybw0014) (git f019674)
  + FluffyMachines Build 1 zh-CN(baoad) (git eb5d6db)
  + DyedBackpacks Build 1 zh-CN(baoad) (git 823de85)
  + SoundMuffler Build 1 zh-CN(baoad) (git b1678a8)
  + DreamCleaner 1.1.2-SNAPSHOT
  + InfinityExpansion 126 zh-CN
  + Networks Build 35 zh-CN(ybw0014) (git ae9012b)
  + DynaTech Build 24 zh-CN(ybw0014) (git ca7d8c6)
  + SlimeTinker Build 32 zh-CN(ybw0014) (git 25590ea)
  + eco 6.25.2
  + StatTrackers 4.3.0
  + EcoSkills 1.20.22
  + Talismans 5.26.0
  + Reforges 4.45.0
  + ProtectionLib 0.9.3
  + ClueScrolls 4.7.1
  + BattlePass 3.6.6
  + BossMania 1.7.50
  + CMILib 1.1.2.0
  + CMI 9.1.3.0
  + MobFarmManager 2.0.2.1
  + CrateReloaded 2.0.35
  + EcoEnchants 8.43.4
  + Residence 5.0.1.3
  + Pet 3.4.3
  + EcoEnchantsGUI 4.1

Block Info:
  World: zy
  X: -1079
  Y: 64
  Z: 524
  Material: MAGENTA_STAINED_GLASS
  Block Data: org.bukkit.craftbukkit.v1_18_R1.block.data.CraftBlockData
  State: org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: NTW_GRABBER
  Inventory: true
  Data: {"id":"NTW_GRABBER","uuid":"34a7128f-ee42-3fcf-8ee6-c0a5e0378109","direction":"NORTH"}

Stacktrace:

java.lang.NoSuchMethodError: 'void io.github.mooy1.infinityexpansion.items.storage.StorageCache.depositAll(org.bukkit.inventory.ItemStack[], boolean)'
        at Networks-Build 35 zh-CN(ybw0014) (git ae9012b).jar//io.github.sefiraat.networks.network.barrel.InfinityBarrel.depositItemStack(InfinityBarrel.java:35)
        at Networks-Build 35 zh-CN(ybw0014) (git ae9012b).jar//io.github.sefiraat.networks.network.barrel.BarrelCore.depositItemStack(BarrelCore.java:15)
        at Networks-Build 35 zh-CN(ybw0014) (git ae9012b).jar//io.github.sefiraat.networks.network.NetworkRoot.addItemStack(NetworkRoot.java:608)
        at Networks-Build 35 zh-CN(ybw0014) (git ae9012b).jar//io.github.sefiraat.networks.slimefun.network.NetworkGrabber.tryGrabItem(NetworkGrabber.java:58)
        at Networks-Build 35 zh-CN(ybw0014) (git ae9012b).jar//io.github.sefiraat.networks.slimefun.network.NetworkGrabber.onTick(NetworkGrabber.java:33)
        at Networks-Build 35 zh-CN(ybw0014) (git ae9012b).jar//io.github.sefiraat.networks.slimefun.network.NetworkDirectional$2.tick(NetworkDirectional.java:99)
        at Slimefun-v4.9-release-2022.01.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
        at Slimefun-v4.9-release-2022.01.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
        at Slimefun-v4.9-release-2022.01.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
        at Slimefun-v4.9-release-2022.01.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ybw0014** [comment]
Handled in qq group, you can close this now, Sefi.
