### ISSUE TITLE
Next Page Issue

### ISSUE THREAD

**Issue by XNarno** [Sefiraat/Networks#7]
When we go to the Crafting Grid or the Network Grid and click on the next page while the Network is empty, it makes an error and it deletes the block.

<details>
  <summary>Error report</summary>
  
Error Generated: 2021-12-21-10-42

Java Environment:
  Operating System: Linux
  Java Version: 17.0.1

Server Software: Paper
  Build: git-Paper-82 (MC: 1.18.1)
  Minecraft v1.18.1-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 987 (git 863b8d64)
  Caused by: Networks vDEV - 2 (git 01461d19)

Installed Addons (19)
  + DankTech2 DEV - 4 (git 803760fb)
  + ExtraGear DEV - 13 (git c62047e2)
  + InfinityExpansion DEV - 126 (git 9a0c8dd5)
  + CMILib 1.1.0.3
  + EMC2 DEV - 11 (git 89b4400a)
  + ChestTerminal DEV - 44 (git 3115957d)
  + HotbarPets DEV - 38 (git fa6c871d)
  + ExoticGarden DEV - 77 (git a2c4b6d3)
  + SoulJars DEV - 23 (git b8358a1f)
  + Networks DEV - 2 (git 01461d19)
  + FoxyMachines DEV - 51 (git 3493db25)
  + DynaTech DEV - 149 (git 4bd5aeef)
  + PrivateStorage DEV - 18 (git 5832db21)
  + ColoredEnderChests DEV - 23 (git 4d041832)
  + FluffyMachines DEV - 94 (git c5a76c49)
  + SimpleUtils DEV - 14 (git 4b1259c7)
  + SlimefunWarfare DEV - 70 (git e2a490bb)
  + SlimeTinker DEV - 53 (git c119a86e)
  + HardcoreSlimefun 1.0

Installed Plugins (89):
  + FarmControl 1.1.8
  + InventoryRollbackPlus 1.6.5
  + DoorsReloaded 1.2.0
  + ColoredSigns 5.0.0
  + PlaceholderAPI 2.10.10
  + ArmoredElytra 2.4.15
  + BetterChairs 1.5.0
  + HolographicDisplays 3.0.0-SNAPSHOT
  + PortableChests 1.5.2
  + ChestSort 12.1.3
  + EnchantSplitter 2.1.0
  + SpeedBoats 1.0
  + UltraRegions 1.6.3
  + RHLeafDecay 1.18_R1
  + RlFire 0.0.1-DEV
  + NoteBlockAPI 1.6.1-SNAPSHOT
  + BossTweaks 1.1
  + ViaVersion 4.1.1
  + Geyser-Spigot 2.0.0-SNAPSHOT
  + NBTAPI 2.9.0-SNAPSHOT
  + Journey 0.1.0-beta
  + LightAPI bukkit-5.1.0 (build SNAPSHOT)
  + HotTools 1.3.0
  + BlueMap 1.7.2
  + UltraEconomy 1.4.5
  + FoodSpoilage 2.0
  + EnderDragonTweaks 1.3.0
  + HiveChecker 3.4.4
  + spark 1.6.4
  + Disenchant-2 1.15a
  + HeapDump 1.4.0
  + UltimateShops 2.2
  + LoneLibs 1.0.16b
  + TeleCraft 1.7.5
  + ProtocolLib 4.8.0-SNAPSHOT-b538
  + LibsDisguises 10.0.26-SNAPSHOT
  + UberEnchant 8.9.3
  + WolfyUtilities 1.8.0.0
  + UltimateTNT 1.11.6
  + NotTooExpensive 1.3.1
  + CommandCooldown 2.4.2
  + Vault 1.7.3-b131
  + UltraPermissions 5.1.7
  + BKCommonLib 1.18.1-v1
  + Vehicles 13.0
  + EpicRename 3.10
  + ComplexTurrets 2.2.2
  + TabTPS 1.3.11
  + Maintenance 3.0.7
  + InfernalMobs 6.6
  + WorldEdit 7.2.8+6008-1246d61
  + Essentials 2.19.2
  + MineableSpawners 3.1.2
  + EvenMoreFish 1.4.3
  + CustomCrafting 1.7.1.3
  + Randomtp 2.19.6
  + CommandPanels 3.17.2.1
  + DiscordSRV 1.24.0
  + EssentialsChat 2.19.2
  + Bookshelf 3.0.7.0
  + HyperPortalBreaking 1.1.2
  + Slimefun DEV - 987 (git 863b8d64)
  + DankTech2 DEV - 4 (git 803760fb)
  + Graves 4.6
  + MeteoritesPro 1.5.3
  + EssentialsSpawn 2.19.2
  + CoreProtect 20.3
  + LevelledMobs 3.3.1 b587
  + ExtraGear DEV - 13 (git c62047e2)
  + InfinityExpansion DEV - 126 (git 9a0c8dd5)
  + CMILib 1.1.0.3
  + Jobs 5.0.1.0
  + EMC2 DEV - 11 (git 89b4400a)
  + ChestTerminal DEV - 44 (git 3115957d)
  + HotbarPets DEV - 38 (git fa6c871d)
  + ExoticGarden DEV - 77 (git a2c4b6d3)
  + SoulJars DEV - 23 (git b8358a1f)
  + BottledExp 3.0.1.1
  + Networks DEV - 2 (git 01461d19)
  + FoxyMachines DEV - 51 (git 3493db25)
  + DynaTech DEV - 149 (git 4bd5aeef)
  + PrivateStorage DEV - 18 (git 5832db21)
  + ColoredEnderChests DEV - 23 (git 4d041832)
  + FluffyMachines DEV - 94 (git c5a76c49)
  + SimpleUtils DEV - 14 (git 4b1259c7)
  + SlimefunWarfare DEV - 70 (git e2a490bb)
  + SlimeTinker DEV - 53 (git c119a86e)
  + PlugManX 2.2.7
  + HardcoreSlimefun 1.0

Block Info:
  World: world
  X: -1023
  Y: 74
  Z: -537
  Material: REDSTONE_LAMP
  Block Data: org.bukkit.craftbukkit.v1_18_R1.block.impl.CraftRedstoneLamp
  State: org.bukkit.craftbukkit.v1_18_R1.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: NTW_CRAFTING_GRID
  Inventory: true
  Data: {"id":"NTW_CRAFTING_GRID"}

Stacktrace:

java.lang.IndexOutOfBoundsException: fromIndex = -20
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.subListRangeCheck(ImmutableCollections.java:272)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.subList(ImmutableCollections.java:266)
	at Networks - DEV 2 (git 01461).jar//io.github.sefiraat.networks.slimefun.network.NetworkCraftingGrid.updateDisplay(NetworkCraftingGrid.java:196)
	at Networks - DEV 2 (git 01461).jar//io.github.sefiraat.networks.slimefun.network.NetworkCraftingGrid$1.tick(NetworkCraftingGrid.java:148)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at Slimefun4 - DEV 987 (git 863b8).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
  

  
</details>

**Comment by Sefiraat** [comment]
Fixed in #8 - thanks for the report :)
