### ISSUE TITLE
Network Grid disappearing

### ISSUE THREAD

**Issue by Skizzles** [Sefiraat/Networks#89]
Error Generated: 2022-07-26-11-22

Java Environment:
  Operating System: Linux
  Java Version: 17.0.2

Server Software: Purpur
  Build: git-Purpur-1697 (MC: 1.19)
  Minecraft v1.19-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 1026 (git 85e8fe81)
  Caused by: Networks vDEV - 41 (git 9c9f1bbb)

Installed Addons (25)
  + EcoPower DEV - 5 (git 5c1ecd68)
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + VoidHarvesters 1.0.0
  + SFCalc DEV - 37 (git dfc0fc41)
  + IslandWipe 1.0.0
  + TranscEndence Skyfactory-34
  + HotbarPets DEV - 38 (git fa6c871d)
  + HeadLimiter DEV - 14 (git 0a02e2fd)
  + ExoticGarden UNOFFICIAL
  + SFMobDrops MODIFIED
  + Networks DEV - 41 (git 9c9f1bbb)
  + ExtraTools 1.2-Void
  + SlimefunOreChunks DEV - 15 (git 2520cb23)
  + DynaTech 1.0.0
  + SlimyTreeTaps DEV - 20 (git 963f0383)
  + FluffyMachines DEV - 118 (git 23a6b1c4)
  + Karma 1.1
  + DyedBackpacks DEV - 17 (git 8b329e96)
  + SupplementalServiceableness 1.0.0
  + LiteXpansion DEV - 180 (git d574b154)
  + SlimeCustomizer DEV - 26 (git 904edca1)
  + CMILib 1.2.2.0
  + CMI 9.2.2.0
  + AdvancedEnchantments 8.12.0
  + Tinkers 3.3.0

Block Info:
  World: SuperiorWorld
  X: -22801
  Y: 98
  Z: 20423
  Material: NOTE_BLOCK
  Block Data: org.bukkit.craftbukkit.v1_19_R1.block.impl.CraftNote
  State: org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: NTW_GRID
  Inventory: true
  Data: {"id":"NTW_GRID"}

Stacktrace:

java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
	at java.base/java.lang.String.contains(String.java:2851)
	at Networks - DEV 41 (git 9c9f1).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.lambda$getEntries$4(AbstractGrid.java:229)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at Networks - DEV 41 (git 9c9f1).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.getEntries(AbstractGrid.java:232)
	at Networks - DEV 41 (git 9c9f1).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.updateDisplay(AbstractGrid.java:156)
	at Networks - DEV 41 (git 9c9f1).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid$1.tick(AbstractGrid.java:112)
	at Slimefun4 - DEV 1026 (git 85e8f).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun4 - DEV 1026 (git 85e8f).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at Slimefun4 - DEV 1026 (git 85e8f).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at Slimefun4 - DEV 1026 (git 85e8f).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Skizzles** [comment]
java.lang.IndexOutOfBoundsException: fromIndex = -48
at java.base/java.util.ImmutableCollections$AbstractImmutableList.subListRangeCheck(ImmutableCollections.java:272)
at java.base/java.util.ImmutableCollections$AbstractImmutableList.subList(ImmutableCollections.java:266)
at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.updateDisplay(AbstractGrid.java:175)
at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid$1.tick(AbstractGrid.java:113)
at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Skizzles** [comment]
@Sefiraat 
Seems this is caused by a player doing the below steps:

using the filter function really fast 
1. set a filter (with typo)
2. set another filter (again with typo)
3. cancel the filter x 2
4.1 immediately set a new filter
4.2 after exiting the grid the network grid disappeared

Was able to reproduce this by doing the same exact steps.
