### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by SrMonsterYT** [Sefiraat/Networks#98]
https://pastebin.com/QJHe9a3L

**Comment by Sefiraat** [comment]
As much as I absolutely hate having bugs in my addons, I cannot do a thing with this report.
I'm sure we've had this discussion before as well, you cannot simply post a report with no context or clues as to why.

Please do a correct report next time.

**Comment by Skizzles** [comment]
@Sefiraat 

I am getting the same errors being thrown, seems the NTW Grid is breaking and turning into a non slimefun block. This seems to happen when someone interacted with their grid after a while of not being online or interacting with it. Seems quite random but I have had 4 cases of this so far.

Different error types:
**ERROR 1**
java.lang.IndexOutOfBoundsException: fromIndex = -48
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.subListRangeCheck(ImmutableCollections.java:272)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.subList(ImmutableCollections.java:266)
	at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.updateDisplay(AbstractGrid.java:175)
	at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid$1.tick(AbstractGrid.java:113)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**ERROR 2**
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "s" is null
	at java.base/java.lang.String.contains(String.java:2851)
	at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.lambda$getEntries$4(AbstractGrid.java:229)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.getEntries(AbstractGrid.java:232)
	at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid.updateDisplay(AbstractGrid.java:157)
	at Networks - DEV 44 (git 2e7bc).jar//io.github.sefiraat.networks.slimefun.network.grid.AbstractGrid$1.tick(AbstractGrid.java:113)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:176)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:146)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:115)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Both lead to the same instance of the Network grid breaking
